jailbreak_table_one:
  prompt_template/jailbreak_prompts_2023_05_07.csv
jailbreak_table_two:
  prompt_template/jailbreak_prompts_2023_12_25.csv

cache_dir:
  models/
address:
  port: 80
  host: "0.0.0.0"

