jailbreak_table_one:
  prompt_template/jailbreak_prompts_2023_05_07.csv
jailbreak_table_two:
  prompt_template/jailbreak_prompts_2023_12_25.csv

cache_dir:
  models/
address:
  port: 8000
  host: "127.0.0.1"

database_parameters:
  user: "postgres"
  password: "root"
  host: "localhost"
  port: "5432"
  database: "mydb"


